### ISSUE TITLE
multiple accessories [feature request]

### ISSUE THREAD

**Issue by nelsonnoah2238** [the-broz/rosuite-issuetracker#1]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
not able to where more then one chest accessory
**Describe the solution you'd like**
maybe a button of some sorts that you can press allowing you to use more then the base accessories making it possible to where more then one chest accessory
**Describe alternatives you've considered**
could also just have it in the background
**Additional context**
loo at the system used in the neighborhood

**Comment by the-broz** [comment]
This seems to be currently possible on the website. I will investigate further later today and update this issue with more info. If you could add more info that would be appreciated such as what type of accessory and a screen recording of the issue if possible. Thanks for your suggestion!

**Comment by the-broz** [comment]
Update: This used to be possible with BTRoblox but their solution has been patched by Roblox. This will be reopened if it becomes possible again.
